"""empty message

Revision ID: 42a7e106e644
Revises: 73757b4ff41d
Create Date: 2023-08-03 15:56:10.441465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42a7e106e644'
down_revision = '73757b4ff41d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('height', sa.Integer(), nullable=True))
        batch_op.drop_column('heigh')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('heigh', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('height')

    # ### end Alembic commands ###
