"""empty message

Revision ID: 73757b4ff41d
Revises: 61e848a1e3bf
Create Date: 2023-08-01 03:07:29.438715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73757b4ff41d'
down_revision = '61e848a1e3bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('rotation_period', sa.Integer(), nullable=True),
    sa.Column('orbital_period', sa.Integer(), nullable=True),
    sa.Column('diameter', sa.Integer(), nullable=True),
    sa.Column('climate', sa.String(length=80), nullable=True),
    sa.Column('gravity', sa.String(length=80), nullable=True),
    sa.Column('terrain', sa.String(length=80), nullable=True),
    sa.Column('surface_water', sa.String(length=80), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('manufacturer', sa.String(length=80), nullable=True),
    sa.Column('cost_in_credits', sa.Integer(), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('max_atmosphering_speed', sa.Integer(), nullable=True),
    sa.Column('crew', sa.String(length=80), nullable=True),
    sa.Column('passengers', sa.Integer(), nullable=True),
    sa.Column('cargo_capacity', sa.Integer(), nullable=True),
    sa.Column('consumables', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicles_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('planets_id', sa.Integer(), nullable=True))
        batch_op.alter_column('people_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'vehicles', ['vehicles_id'], ['id'])
        batch_op.create_foreign_key(None, 'planets', ['planets_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('people_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('planets_id')
        batch_op.drop_column('vehicles_id')

    op.drop_table('vehicles')
    op.drop_table('planets')
    # ### end Alembic commands ###
